### ISSUE TITLE
Starts up fine but then errors when sending data

### ISSUE THREAD

**Issue by tatonki1** [peaksnail/pinpoint-node-agent#20]
Thanks for the plugin - I have it wired up correctly and it starts fine, but when it tries to send data I am getting this error:

[2017-01-25 14:33:40.376] [DEBUG] [HUBOT-B2B]  [Users/n0224265/Documents/Docker/pinpoint-node-agent/agent/socket/udp_client] UDP message sent to 172.17.0.2:9995, size is: 77
[Wed Jan 25 2017 14:33:43 GMT-0500 (EST)] **ERROR TypeError: Cannot read property 'apply' of undefined
  at express0application0handle (/Users/n0224265/Documents/Docker/pinpoint-node-agent/agent/plugins/core/express/wrap.js:248:22)**
  at Object.cb (/Users/n0224265/Documents/Docker/pinpoint-node-agent/agent/commons/trace/method_interceptor.js:41:24)
  at Namespace.run (/Users/n0224265/Documents/Docker/pinpoint-node-agent/agent/commons/cls/index.js:59:5)
  at Function.originalWrapper [as handle] (/Users/n0224265/Documents/Docker/pinpoint-node-agent/agent/commons/trace/method_interceptor.js:40:23)
  at Server.app (/Users/n0224265/Documents/Chatbot/hubot-b2b-0/node_modules/connect/lib/connect.js:67:37)
  at Server.<anonymous> (/Users/n0224265/Documents/Chatbot/hubot-b2b-0/node_modules/engine.io/lib/server.js:443:22)
  at Server.<anonymous> (/Users/n0224265/Documents/Chatbot/hubot-b2b-0/node_modules/socket.io/lib/index.js:260:16)
  at emitTwo (events.js:106:13)
  at Server.emit (events.js:191:7)
  at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:547:12)
  at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)

**Comment by tatonki1** [comment]
Correction -when I try to load my node.js application in my browser I get the above error....

**Comment by tatonki1** [comment]
## ### Not sure if the 3 deprecated libraries have anything to do with this...


LIBP45P-16600WL:Docker n0224265$ cd pinpoint-node-agent/

LIBP45P-16600WL:pinpoint-node-agent n0224265$ ls
README.md	agent		index.js	package.json	test

LIBP45P-16600WL:pinpoint-node-agent n0224265$ nam install

npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> ws@0.4.32 install /Users/n0224265/Documents/Docker/pinpoint-node-agent/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
pinpoint-node-agent@2.2.0 /Users/n0224265/Documents/Docker/pinpoint-node-agent
├─┬ async-listener@0.6.3 
│ └── shimmer@1.0.0 
├── bluebird@3.4.7 
├─┬ chai@3.5.0 
│ ├── assertion-error@1.0.2 
│ ├─┬ deep-eql@0.1.3 
│ │ └── type-detect@0.1.1 
│ └── type-detect@1.0.0 
├── continuation-local-storage@3.2.0 
├── cpu-usage@0.1.0 
├─┬ emitter-listener@1.0.1 
│ └── shimmer@1.0.0 
├── later@1.2.0 
├── lodash@4.17.4 
├─┬ log4js@0.6.38 
│ ├─┬ readable-stream@1.0.34 
│ │ ├── core-util-is@1.0.2 
│ │ ├── inherits@2.0.3 
│ │ ├── isarray@0.0.1 
│ │ └── string_decoder@0.10.31 
│ └── semver@4.3.6 
├─┬ mocha@2.5.3 
│ ├── commander@2.3.0 
│ ├─┬ debug@2.2.0 
│ │ └── ms@0.7.1 
│ ├── diff@1.4.0 
│ ├── escape-string-regexp@1.0.2 
│ ├─┬ glob@3.2.11 
│ │ └─┬ minimatch@0.3.0 
│ │   ├── lru-cache@2.7.3 
│ │   └── sigmund@1.0.1 
│ ├── growl@1.9.2 
│ ├─┬ jade@0.26.3 
│ │ ├── commander@0.6.1 
│ │ └── mkdirp@0.3.0 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ ├── supports-color@1.2.0 
│ └── to-iso-string@0.0.2 
├── moment@2.17.1 
├── node-int64@0.4.0 
├─┬ node-schedule@1.2.0 
│ ├── cron-parser@1.1.0 
│ └── long-timeout@0.0.2 
├── pidusage@1.1.0 
├─┬ shelljs@0.7.6 
│ ├─┬ glob@7.1.1 
│ │ ├── fs.realpath@1.0.0 
│ │ ├─┬ inflight@1.0.6 
│ │ │ └── wrappy@1.0.2 
│ │ ├─┬ minimatch@3.0.3 
│ │ │ └─┬ brace-expansion@1.1.6 
│ │ │   ├── balanced-match@0.4.2 
│ │ │   └── concat-map@0.0.1 
│ │ ├── once@1.4.0 
│ │ └── path-is-absolute@1.0.1 
│ ├── interpret@1.0.1 
│ └─┬ rechoir@0.6.2 
│   └── resolve@1.2.0 
├── shimmer@1.1.0 
├── stack-trace@0.0.9 
├─┬ thrift@0.9.3 
│ ├── node-int64@0.3.3 
│ ├── q@1.0.1 
│ └─┬ ws@0.4.32 
│   ├── commander@2.1.0 
│   ├── nan@1.0.0 
│   ├── options@0.0.6 
│   └── tinycolor@0.0.1 
└─┬ util@0.10.3 
  └── inherits@2.0.1

**Comment by peaksnail** [comment]
hi, this agent is developed for node server and I haven't test it in browser, I doubt there is some problem with compatibility.
