### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by forestpro** [peaksnail/pinpoint-node-agent#27]
[[32m[2017-06-16 10:17:44.657] [INFO] [node-easydata-test]^[[39m  [pinpoint-node-agent/agent/commons/agent] start to hack module load
/opt/nodejs/easyData/pinpoint-node-agent/agent/commons/module/module_load.js:73
    if (module_name.startsWith('.') || module_name.startsWith('/')) {
                    ^
TypeError: undefined is not a function
    at Function._module._load (/opt/nodejs/easyData/pinpoint-node-agent/agent/commons/module/module_load.js:73:21)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.loadPluginsApiDetails (/opt/nodejs/easyData/pinpoint-node-agent/agent/commons/module/module_load.js:103:23)
    at Agent.hackModuleLoad (/opt/nodejs/easyData/pinpoint-node-agent/agent/commons/agent.js:59:43)
    at Object.<anonymous> (/opt/nodejs/easyData/pinpoint-node-agent/index.js:39:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by forestpro** [comment]
求救，这是什么原因导致的呢？

**Comment by peaksnail** [comment]
麻烦提供 node 版本，pinpoint-node-agent 启动参数和具体使用方法

**Comment by forestpro** [comment]
[root@localhost ~]# node -v
v0.12.2

使用方法就是接在index.js 里头部加入：
require('./pinpoint-node-agent');

**Comment by peaksnail** [comment]
node 版本太低了，使用最新的版本试一下吧

**Comment by forestpro** [comment]
好吧。哈哈，我试试
